### ISSUE TITLE
Arret du chat à trois reprise durant un live

### ISSUE THREAD

**Issue by Glaudioman** [JohnXLivingston/xmppjs-chat-bot#4]
[logs peertube.txt](https://github.com/JohnXLivingston/xmppjs-chat-bot/files/14322511/logs.peertube.txt)

Suite au test de live, le service prosody était ko à trois reprises (test pendant environ 1h)

Pas de flux de message particuliers, entre 70 et 100 personnes connectées en simultanées.

**Comment by JohnXLivingston** [comment]
Merci pour le retour.

Y'a rien dans l'outils de diagnostic, tout en bas, après "Prosody error log (last 50 lines)" ?

**Comment by JohnXLivingston** [comment]
Oups, mauvais dépot. Ça devait être pour https://github.com/JohnXLivingston/peertube-plugin-livechat/issues
@Glaudioman , tu peux recréer le ticket là bas stp ?

**Comment by JohnXLivingston** [comment]
Je ferme. Ça ne concerne pas le bot, ni le plugin de tchat (cf échanges mails).
